---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: debian-7.9

suites:
  - name: default
    run_list:
      - recipe[cmake::default]
    attributes:
      cmake:
        major: 3.4
        minor: 1
